---
title: "Spotify Blog Post HW2"
author: "Emily Peters"
categories: [python]
---

In [46]:
import pandas as pd
spotify = pd.read_csv('https://bcdanl.github.io/data/spotify_all.csv')
spotify

,pid,playlist_name,pos,artist_name,track_name,duration_ms,album_name
0,0,Throwbacks,0,Missy Elliott,Lose Control (feat. Ciara & Fat Man Scoop),226863,The Cookbook
1,0,Throwbacks,1,Britney Spears,Toxic,198800,In The Zone
2,0,Throwbacks,2,Beyoncé,Crazy In Love,235933,Dangerously In Love (Alben für die Ewigkeit)
3,0,Throwbacks,3,Justin Timberlake,Rock Your Body,267266,Justified
4,0,Throwbacks,4,Shaggy,It Wasn't Me,227600,Hot Shot
...,...,...,...,...,...,...,...
198000,999998,✝️,6,Chris Tomlin,Waterfall,209573,Love Ran Red
198001,999998,✝️,7,Chris Tomlin,The Roar,220106,Love Ran Red
198002,999998,✝️,8,Crowder,Lift Your Head Weary Sinner (Chains),224666,Neon Steeple
198003,999998,✝️,9,Chris Tomlin,We Fall Down,280960,How Great Is Our God: The Essential Collection
198004,999998,✝️,10,Caleb and Kelsey,"10,000 Reasons / What a Beautiful Name",178189,"10,000 Reasons / What a Beautiful Name"

Cody Johnson has been one of my favorite artists to listen to recently, so his name caught my eye while looking through the spotify data frame.

In [47]:
artist= spotify.query("artist_name=='Cody Johnson'")
artist

,pid,playlist_name,pos,artist_name,track_name,duration_ms,album_name
502,9,old country,9,Cody Johnson,Diamond In My Pocket,196906,A Different Day
30193,456,Country,56,Cody Johnson,Dance Her Home,174680,Cowboy Like Me
30194,456,Country,57,Cody Johnson,Me and My Kind,156200,Cowboy Like Me
30195,456,Country,58,Cody Johnson,Texas Kind Of Way,249573,Six Strings One Dream
30197,456,Country,60,Cody Johnson,Diamond In My Pocket,196906,A Different Day
30198,456,Country,61,Cody Johnson,Lucky,186813,Cowboy Like Me
30235,456,Country,98,Cody Johnson,18 Wheels,180040,A Different Day
30236,456,Country,99,Cody Johnson,Jesus Ain't Watching,219120,A Different Day
30237,456,Country,100,Cody Johnson,Ride With Me,215600,A Different Day
30238,456,Country,101,Cody Johnson,Chain Drinkin',189760,Gotta Be Me
30239,456,Country,102,Cody Johnson,Grass Stains,190093,Gotta Be Me
30240,456,Country,103,Cody Johnson,Billy's Brother,183040,Gotta Be Me
30258,456,Country,121,Cody Johnson,With You I Am,220893,Gotta Be Me
30259,456,Country,122,Cody Johnson,Wild as You,186066,Gotta Be Me
30260,456,Country,123,Cody Johnson,Kiss Goodbye,200786,Gotta Be Me
30262,456,Country,125,Cody Johnson,Proud,205946,Cowboy Like Me
30263,456,Country,126,Cody Johnson,Give a Cowboy a Kiss,305013,Cowboy Like Me
30264,456,Country,127,Cody Johnson,I Know My Way Back (Clara's Song),205893,Gotta Be Me
30265,456,Country,128,Cody Johnson,Cowboy Like Me,302124,Cowboy Like Me
30266,456,Country,129,Cody Johnson,I Ain't Going Nowhere Baby,277160,Gotta Be Me
30269,456,Country,132,Cody Johnson,Keep Her Man,198426,A Different Day
30271,456,Country,134,Cody Johnson,I Don't Care About You,238400,A Different Day
30272,456,Country,135,Cody Johnson,Never Go Home Again,252146,Cowboy Like Me
30273,456,Country,136,Cody Johnson,Half a Song,211506,Gotta Be Me
30274,456,Country,137,Cody Johnson,Every Scar Has a Story,208160,Gotta Be Me
45608,680,Country Favorites,229,Cody Johnson,Texas Kind Of Way,249573,Six Strings One Dream
45613,680,Country Favorites,234,Cody Johnson,The Only One I Know (Cowboy Life),239320,Gotta Be Me
67453,998,Country,102,Cody Johnson,With You I Am,220893,Gotta Be Me
75623,1125,summer music,70,Cody Johnson,Diamond In My Pocket,196906,A Different Day
100834,1501,band songs,21,Cody Johnson,Diamond In My Pocket,196906,A Different Day
110576,1642,driving music,224,Cody Johnson,Guilty As Can Be,242720,A Different Day
118340,1773,Chill,74,Cody Johnson,Jesse's Name,274854,Black and White Label
131620,1957,summer,6,Cody Johnson,Me and My Kind,156200,Cowboy Like Me
136414,999032,Walk Up Songs,5,Cody Johnson,I Know My Way Back (Clara's Song),205893,Gotta Be Me
151883,999265,Red Dirt,50,Cody Johnson,Me and My Kind,156200,Cowboy Like Me
151884,999265,Red Dirt,51,Cody Johnson,Dance Her Home,174680,Cowboy Like Me
177107,999668,Texas Forever,72,Cody Johnson,Wild as You,186066,Gotta Be Me
177108,999668,Texas Forever,73,Cody Johnson,With You I Am,220893,Gotta Be Me
177109,999668,Texas Forever,74,Cody Johnson,Me and My Kind,156200,Cowboy Like Me
177110,999668,Texas Forever,75,Cody Johnson,Diamond In My Pocket,196906,A Different Day
177111,999668,Texas Forever,76,Cody Johnson,Dance Her Home,174680,Cowboy Like Me
177138,999668,Texas Forever,103,Cody Johnson,Texas Kind Of Way,249573,Six Strings One Dream
177142,999668,Texas Forever,107,Cody Johnson,Ride With Me,215600,A Different Day
177148,999668,Texas Forever,113,Cody Johnson,Give a Cowboy a Kiss,305013,Cowboy Like Me
187105,999828,Texas Country,54,Cody Johnson,Dance Her Home,174680,Cowboy Like Me
187106,999828,Texas Country,55,Cody Johnson,Diamond In My Pocket,196906,A Different Day
187132,999828,Texas Country,81,Cody Johnson,Me and My Kind,156200,Cowboy Like Me
187157,999828,Texas Country,106,Cody Johnson,With You I Am,220893,Gotta Be Me
187172,999828,Texas Country,121,Cody Johnson,Texas Kind Of Way,249573,Six Strings One Dream

In [ ]:
artist['playlist_name'].nunique()

12

Cody Johnson's music appeared in 12 different playlists.

In [48]:
tracks=(
    artist
    .drop_duplicates(subset=['track_name'])
    ['track_name'].nunique()
)
tracks

27

In [49]:
artist['album_name'].nunique()

5

27 different songs were featured, and they were from 5 different albums.

In [ ]:
artist['duration_min']=artist['duration_ms']/60000
artist['duration_min'].mean()

On average, Cody Johnson's songs are 3.53 minutes long.

In [51]:
total_ms= artist['duration_ms'].sum()
total_ms

10368578

In [ ]:
total_ms/60000

172.80963333333332

Playing all of Cody Johnson's music from spotify will take 172.81 minutes.